const PORT = process.env.PORT ||8000
const DATABASE_URL = process.env.DATABASE_URL
const DATABASE_URL1 = process.env.DATABASE_URL1
const DATABASE_NAME = process.env.DATABASE_NAME
const CORS_ORIGIN = process.env.CORS_ORIGIN
const CLOUD_NAME = process.env.CLOUD_NAME
const CLOUD_API_KEY = process.env.API_KEY
const CLOUD_API_SECRET = process.env.API_SECRET
const ACCESS_TOKEN = process.env.ACCESS_TOKEN
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY
const REFRESH_TOKEN = process.env.REFRESH_TOKEN_EXPIRY
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN

export {
    PORT,
    DATABASE_URL,
    DATABASE_URL1,
    DATABASE_NAME,
    CORS_ORIGIN,
    CLOUD_NAME,
    CLOUD_API_KEY,
    CLOUD_API_SECRET,
    ACCESS_TOKEN,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRY
 
}